### ISSUE TITLE
Options page is not working in Firefox

### ISSUE THREAD

**Issue by Alex-302** [sharat87/inhuman-time#2]
v0.5.0

<details>
<summary>Details</summary>

![image](https://github.com/sharat87/inhuman-time/assets/8361299/8bcfb80a-6819-49de-9941-a120fdb91988)

</details>

**Comment by sharat87** [comment]
Just submitted fixed version with the missing options page. Awaiting review. 🤞
Thanks for reporting. 🙏

**Comment by sharat87** [comment]
Fixed. Please update. 🙂

![shot-2023-06-09-08-37-30](https://github.com/sharat87/inhuman-time/assets/120119/c12d39a3-112e-4a33-a971-5a569ace3093)

**Comment by Alex-302** [comment]
Thanks!
Now it works, but I can't apply that settings (tried to press Enter, switching tabs and restart the extension. Sure, GH page also refreshed:) ). Which line should I enter to get 24h format?

**Comment by Alex-302** [comment]
Checked `HH:mm, DD MMM YYYY` 

* Firefox with **v0.8** => `19:26, 08 Jun 2023` (24h format is good for me)
* Chrome with **v0.6** => `undefined`

Will 0.8 be available for Chrome? I see `0.6` in the [last commit](https://github.com/sharat87/inhuman-time/commit/f76c94e2ab55c6b9446bfe6f6da842a63a42fe8c#diff-6bc2c0b5164076a1b57b067398be19a40d2b8efa3428b03504562ea88593866cR4) 

~Btw. Chrome uses 12h format, and I can't change it - `local` uses Chrome's choose - 12h, but system format is 24H.~
solved by `English (Canada)` in Chrome lang settings.

**Comment by sharat87** [comment]
Yeah, the Chrome team is still reviewing 0.6, and won't let me upload 0.8 until that's reviewed. 🤦

Anyway, I'll push the changes now, since Firefox has already approved. 🙂
