### ISSUE TITLE
The extension is not available in Chrome Store anymore

### ISSUE THREAD

**Issue by Alex-302** [sharat87/inhuman-time#3]
<details>
<summary>Details</summary>

![image](https://github.com/sharat87/inhuman-time/assets/8361299/73a78907-b9b8-40bd-8e71-038c7cec69c1)

</details>

Could you please upload CRX to github, if Google banned you?

**Comment by sharat87** [comment]
Hey, thanks for reaching out. I didn't realize people were still using this extension. I'll get this fixed soon.

**Comment by sharat87** [comment]
Turns out it got taken down because of the options page issue that you raised at #2. 🙂
Fixed it and uploaded new version. 🤞

**Comment by Alex-302** [comment]
> I didn't realize people were still using this extension

Just that nobody knows about it)



> Fixed it and uploaded new version.

Thanks, waiting:)

**Comment by Alex-302** [comment]
Now it is available) 
Thanks.
